sudo: required

language: python

services:
    - docker

python:
    - "2.7"
    - "3.5"

install:
    - pip install -r foobar/requirements.txt
    - docker build -t foobar .
    - docker run -d -p 8000:5000 foobar

script: py.test

